// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv8YSNbasXrLMy8y7SqW0CeVByyHxMszE',
    appId: '1:952286946774:web:d8eea4d8d5741c78ce7077',
    messagingSenderId: '952286946774',
    projectId: 'adm-vitrine-db',
    authDomain: 'adm-vitrine-db.firebaseapp.com',
    databaseURL: 'https://adm-vitrine-db-default-rtdb.firebaseio.com',
    storageBucket: 'adm-vitrine-db.appspot.com',
    measurementId: 'G-71W4H62ZXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBscEMRTuWRoGxiqg9n-o0S9Xz_ZpSW55A',
    appId: '1:952286946774:android:d3de43625c777877ce7077',
    messagingSenderId: '952286946774',
    projectId: 'adm-vitrine-db',
    databaseURL: 'https://adm-vitrine-db-default-rtdb.firebaseio.com',
    storageBucket: 'adm-vitrine-db.appspot.com',
  );
}
