// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBx7bN930O6Pnrb60QjoVDFcnXT8spP7Y',
    appId: '1:846106556704:web:6f8a823b352a57bb6eff45',
    messagingSenderId: '846106556704',
    projectId: 'vitrine-db-e4b2d',
    authDomain: 'vitrine-db-e4b2d.firebaseapp.com',
    storageBucket: 'vitrine-db-e4b2d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVUyxtHr7abPX7l-LW2CoTIk4ypA32kc4',
    appId: '1:846106556704:android:a0b309e7d79f1d9b6eff45',
    messagingSenderId: '846106556704',
    projectId: 'vitrine-db-e4b2d',
    storageBucket: 'vitrine-db-e4b2d.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBx7bN930O6Pnrb60QjoVDFcnXT8spP7Y',
    appId: '1:846106556704:web:e246f9779f54a41f6eff45',
    messagingSenderId: '846106556704',
    projectId: 'vitrine-db-e4b2d',
    authDomain: 'vitrine-db-e4b2d.firebaseapp.com',
    storageBucket: 'vitrine-db-e4b2d.appspot.com',
  );

}